trigger:
- master
- dev/*
- release/*

pr:
- master
- dev/*
- release/*

pool:
  vmImage: windows-latest

variables:
  Build.Configuration: Release
  DotNet.Tools: $(Agent.ToolsDirectory)/dotnet
  DotNet.Version: 7.0.x

jobs:
- job: Build
  displayName: Build and Test solution
  steps:
  - checkout: self
    displayName: Checkout
    fetchDepth: 0

  # Cache .NET SDKs and Tools across pipeline runs
  - task: Cache@2
    displayName: Cache .NET SDKs
    inputs:
      key: 'dotnet | "$(Agent.OS)" | "$(DotNet.Version)"'
      restoreKeys: |
        dotnet | "$(Agent.OS)"
        dotnet
      path: $(DotNet.Tools)

  # Install the .NET 7 SDK
  - task: UseDotNet@2
    displayName: Install the .NET 7 SDK
    inputs:
      version: $(DotNet.Version)
      performMultiLevelLookup: true

  # Set Build Version
  - script: nbgv cloud
    displayName: Set NBGV version

  # Restore solution
  - script: dotnet restore -p:Configuration=$(Build.Configuration)
    displayName: Restore solution

  # Build solution
  - script: dotnet build --no-restore -c $(Build.Configuration)
    displayName: Build solution

  # Run .NET 7 unit tests
  - script: dotnet test --no-build -c $(Build.Configuration) -l "trx;LogFileName=VSTestResults_net7.0.trx"
    displayName: Run .NET 7 unit tests

  # Publish test results
  - task: PublishTestResults@2
    displayName: Publish test results
    inputs:
      testResultsFormat: VSTest
      testResultsFiles: '**/TestResults/VSTestResults*.trx'
    condition: always()

  # Pack solution
  - script: dotnet pack --no-build -c $(Build.Configuration)
    displayName: Pack solution
 
  # Publish build artifacts
  - publish: bin/nupkg
    artifact: Packages
    displayName: Publish package artifacts